# -*- coding: utf-8 -*-
"""Syslognew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnAFoXFP2yL28XtVoyEToX5xgOPz-f4W
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix, roc_curve, auc
)
import graphviz
import os
import warnings
warnings.filterwarnings('ignore')

# 1. Generate Synthetic Syslog Data
def generate_syslog_data(num_entries=10000):  # Updated to 10,000
    timestamps = [datetime.now() - timedelta(minutes=random.randint(1, 10000)) for _ in range(num_entries)]
    hostnames = [f"192.168.1.{random.randint(1, 255)}" for _ in range(num_entries)]
    messages = [random.choice(["Failed login attempt", "Connection timeout", "DDoS detected",
                               "Normal operation", "High CPU usage"]) for _ in range(num_entries)]
    labels = [1 if "DDoS" in msg else 0 for msg in messages]
    return pd.DataFrame({"Timestamp": timestamps, "Source IP": hostnames, "Message": messages, "Label": labels})

# Generate and save synthetic data
synthetic_data = generate_syslog_data(num_entries=10000)
synthetic_data.to_csv("synthetic_syslog.csv", index=False)

# 2. Preprocess Function
def preprocess_data(df):
    df.columns = df.columns.str.strip()

    def parse_syslog_timestamp(ts):
        try:
            dt = datetime.strptime(ts.strip(), "%b %d %H:%M:%S")
            return dt.replace(year=datetime.now().year)
        except:
            try:
                return pd.to_datetime(ts, errors='coerce')
            except:
                return pd.NaT

    df['Timestamp'] = df['Timestamp'].astype(str).apply(parse_syslog_timestamp)
    df = df.dropna(subset=['Timestamp'])
    df['Timestamp'] = df['Timestamp'].astype(np.int64) / 1e9

    ip_column_candidates = ['Source IP', 'Src IP', 'IP', 'Hostname']
    found_ip_column = next((col for col in ip_column_candidates if col in df.columns), None)

    if found_ip_column:
        df['Source IP'] = df[found_ip_column]
        label_encoder = LabelEncoder()
        df['Source IP'] = label_encoder.fit_transform(df['Source IP'])
    else:
        raise KeyError("No valid IP/Hostname column found in: " + str(df.columns.tolist()))

    return df

# 3. Load and Preprocess Data
real_syslog_path = "/content/Syslog.csv"
real_syslog_data = pd.read_csv(real_syslog_path)
real_syslog_data.columns = real_syslog_data.columns.str.strip()
real_syslog_data = preprocess_data(real_syslog_data)

synthetic_data = pd.read_csv("synthetic_syslog.csv")
synthetic_data = preprocess_data(synthetic_data)

# 4. Prepare Dataset
X = synthetic_data[['Timestamp', 'Source IP']]
y = synthetic_data['Label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

# 5. Evaluation & Visualization
performance_metrics = []

for name, model in models.items():
    print(f"\n--- {name} ---")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    print(f"Accuracy: {acc:.2f}")
    print(classification_report(y_test, y_pred))

    performance_metrics.append({
        "Model": name,
        "Accuracy": acc,
        "Precision": classification_report(y_test, y_pred, output_dict=True)['1']['precision'],
        "Recall": classification_report(y_test, y_pred, output_dict=True)['1']['recall'],
        "F1 Score": classification_report(y_test, y_pred, output_dict=True)['1']['f1-score'],
    })

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(4, 3))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f"{name} - Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.tight_layout()
    plt.show()

    # ROC Curve
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    roc_auc = auc(fpr, tpr)
    plt.figure(figsize=(5, 4))
    plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.2f})")
    plt.plot([0, 1], [0, 1], 'k--')
    plt.title(f"{name} - ROC Curve")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.legend()
    plt.tight_layout()
    plt.show()

    # Feature Importance
    if hasattr(model, 'feature_importances_'):
        plt.figure(figsize=(4, 3))
        sns.barplot(x=model.feature_importances_, y=X.columns)
        plt.title(f"{name} - Feature Importance")
        plt.tight_layout()
        plt.show()

    # DOT Graph for Decision Tree
    if name == "Decision Tree":
        dot_file = "tree.dot"
        export_graphviz(model, out_file=dot_file, feature_names=X.columns,
                        class_names=["Normal", "DDoS"], filled=True)
        with open(dot_file) as f:
            dot_graph = f.read()
        graph = graphviz.Source(dot_graph)
        graph.render("decision_tree", format="png", cleanup=True)
        graph.view()

# 6. Performance Summary
performance_df = pd.DataFrame(performance_metrics)
print("\n📊 Model Performance Summary:")
print(performance_df.to_string(index=False))

# 7. Additional Visualizations

# Timestamp Distribution of Events
synthetic_data['Readable Time'] = pd.to_datetime(synthetic_data['Timestamp'], unit='s')
plt.figure(figsize=(10, 4))
sns.histplot(data=synthetic_data, x='Readable Time', hue='Label', bins=50, palette='coolwarm', kde=True)
plt.title("Distribution of Syslog Events Over Time")
plt.xlabel("Time")
plt.ylabel("Event Count")
plt.tight_layout()
plt.show()

# Message Type Distribution
plt.figure(figsize=(8, 4))
sns.countplot(data=synthetic_data, y='Message', hue='Label', palette='magma')
plt.title("Syslog Message Type Distribution (DDoS vs Normal)")
plt.xlabel("Count")
plt.ylabel("Message Type")
plt.tight_layout()
plt.show()

# Source IP Frequency
top_ips = synthetic_data['Source IP'].value_counts().head(10)
plt.figure(figsize=(8, 4))
sns.barplot(x=top_ips.values, y=top_ips.index, palette='viridis')
plt.title("Top 10 Most Active Source IPs")
plt.xlabel("Log Count")
plt.ylabel("Source IP")
plt.tight_layout()
plt.show()

# Pairplot of Features
pairplot_df = synthetic_data[['Timestamp', 'Source IP', 'Label']]
sns.pairplot(pairplot_df, hue='Label', palette='Set2', corner=True)
plt.suptitle("Pairwise Feature Relationships", y=1.02)
plt.show()

# Correlation Heatmap
plt.figure(figsize=(5, 3))
corr = synthetic_data[['Timestamp', 'Source IP', 'Label']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Between Features")
plt.tight_layout()
plt.show()

# Line Graph of Model Metrics
metrics_to_plot = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
plt.figure(figsize=(8, 5))
for metric in metrics_to_plot:
    plt.plot(performance_df['Model'], performance_df[metric], marker='o', label=metric)

plt.title("Model Comparison - Performance Metrics")
plt.xlabel("Model")
plt.ylabel("Score")
plt.ylim(0, 1.1)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# 8. Predict on Real Syslog Data
X_real = real_syslog_data[['Timestamp', 'Source IP']]
if not X_real.empty:
    X_real_scaled = scaler.transform(X_real)

    for name, model in models.items():
        real_predictions = model.predict(X_real_scaled)
        real_syslog_data[f'{name} Prediction'] = real_predictions

    real_syslog_data.to_csv("predicted_syslog_with_all_models.csv", index=False)
    print("\n✅ Predictions saved to predicted_syslog_with_all_models.csv")
else:
    print("\n⚠️ Real syslog data is empty after preprocessing.")